set encoding=utf-8
set fileencodings=utf-8,chinese,latin-1
if has("win32")
"set fileencoding=chinese
set fileencoding=utf-8
else
set fileencoding=utf-8
endif
"解决菜单乱码
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim
"解决consle输出乱码
language messages zh_CN.utf-8
syntax on
set number

set hlsearch
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set backupdir=e:\vim_backup
set undodir=e:\vim_backup
set autoindent
set listchars=tab:>-,trail:-,space:-
filetype plugin on
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_toc_autofit = 1
set guifont=DejaVu_Sans_Mono:h10
set guifontwide=KaiXinSong:h10
colorscheme evening
set backspace=2
set backspace=indent,eol,start
set ff=unix
