set encoding=utf-8
syntax on
set number

set hlsearch
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set backupdir=e:\vim_backup
set undodir=e:\vim_backup
set guifont=DejaVu_Sans_Mono:h10
set guifontwide=KaiXinSong:h10
set listchars=tab:>-,trail:-
